# Generated by Django 5.1.6 on 2025-02-18 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='tipo',
            field=models.CharField(choices=[('estadual', 'Estadual Regular'), ('indigena', 'Indígena')], default='estadual', max_length=10, verbose_name='Tipo de Escola'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve conter 10 ou 11 dígitos')]),
        ),
    ]
