# Generated by Django 5.1.6 on 2025-02-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_cep_remove_cnpj'),
        ('core', '0003_escola_tipo_alter_escola_telefone'),
    ]

    operations = [
    ]
